(function(){
'use strict';
const css=`#ms-ai{position:fixed;right:20px;bottom:20px;z-index:9999;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}#ms-ai *{box-sizing:border-box}.ms-launch{width:58px;height:58px;border:0;border-radius:50%;background:#071b33;color:#fff;box-shadow:0 12px 35px #071b3340;font-size:23px;cursor:pointer}.ms-panel{position:absolute;right:0;bottom:70px;width:min(390px,calc(100vw - 28px));height:min(620px,calc(100vh - 105px));background:#fff;border:1px solid #dfe6ed;border-radius:16px;box-shadow:0 24px 70px #071b3330;display:none;overflow:hidden}.ms-panel.open{display:flex;flex-direction:column}.ms-head{background:#071b33;color:#fff;padding:15px}.ms-headrow{display:flex;justify-content:space-between;align-items:center}.ms-title{font-weight:900;font-size:14px}.ms-sub{font-size:9px;opacity:.65;margin-top:3px}.ms-x{border:0;background:none;color:#fff;font-size:22px}.ms-mode{display:flex;gap:5px;margin-top:11px}.ms-mode button{flex:1;border:1px solid #ffffff22;background:#ffffff0d;color:#cbd7e3;border-radius:7px;padding:7px;font-size:9px;font-weight:800}.ms-mode button.active{background:#fff;color:#071b33}.ms-msgs{flex:1;overflow:auto;padding:14px;background:#f6f8fa}.ms-msg{max-width:88%;padding:9px 11px;border-radius:11px;margin:7px 0;font-size:11px;line-height:1.45;white-space:pre-wrap}.ms-msg.bot{background:#fff;border:1px solid #e1e7ed}.ms-msg.user{margin-left:auto;background:#1261a0;color:#fff}.ms-quick{display:flex;gap:6px;overflow:auto;padding:9px 10px;border-top:1px solid #e6ebef}.ms-quick button{white-space:nowrap;border:1px solid #dfe6ed;background:#fff;border-radius:99px;padding:6px 9px;font-size:9px;font-weight:800}.ms-compose{display:flex;gap:7px;padding:10px;border-top:1px solid #dfe6ed;background:#fff}.ms-input{flex:1;resize:none;border:1px solid #dfe6ed;border-radius:9px;padding:9px;font:inherit;font-size:11px;outline:none}.ms-send{width:40px;border:0;border-radius:9px;background:#1261a0;color:#fff;font-weight:900}.ms-typing{font-size:9px;color:#708096;padding:0 10px 7px;display:none}.ms-typing.show{display:block}.ms-link{color:#1261a0;text-decoration:underline;cursor:pointer}`;
const s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
const root=document.createElement('div');root.id='ms-ai';root.innerHTML=`<div class="ms-panel" id="msPanel"><div class="ms-head"><div class="ms-headrow"><div><div class="ms-title">Milestone AI Assistant</div><div class="ms-sub">Fleet, tyre, workshop & client support</div></div><button class="ms-x" id="msClose">×</button></div><div class="ms-mode"><button class="active" data-mode="staff">STAFF</button><button data-mode="client">CLIENT</button></div></div><div class="ms-msgs" id="msMsgs"></div><div class="ms-typing" id="msTyping">Assistant is thinking…</div><div class="ms-quick"><button data-q="Show me today's critical tyre alerts">Critical tyres</button><button data-q="What is the breakdown situation?">Breakdowns</button><button data-q="How do I perform a tyre inspection?">Inspection help</button><button data-q="What services does Milestone offer?">Services</button></div><form class="ms-compose" id="msForm"><textarea class="ms-input" id="msInput" rows="1" placeholder="Ask anything…"></textarea><button class="ms-send">➤</button></form></div><button class="ms-launch" id="msLaunch" aria-label="Open AI assistant">✦</button></div>`;document.body.appendChild(root);
let mode='staff',history=[];
const $=id=>document.getElementById(id);
function add(text,who){const d=document.createElement('div');d.className='ms-msg '+who;d.textContent=text;$('msMsgs').appendChild(d);$('msMsgs').scrollTop=$('msMsgs').scrollHeight}
function db(){try{return JSON.parse(localStorage.getItem('milestoneDB_v2')||'{}')}catch{return {}}}
function context(){const d=db();return {vehicles:d.vehicles||[],tyres:d.tyres||[],inspections:d.inspections||[],breakdowns:d.breakdowns||[],retreads:d.retreads||[],scrap:d.scrap||[]}}
function localAnswer(q){const d=context(),l=q.toLowerCase();const critical=d.tyres.filter(x=>/critical/i.test(x[6]||''));const open=d.breakdowns.filter(x=>/open/i.test(x[5]||''));
if(/critical|low rtd|tyre alert|danger/.test(l))return `I can see ${critical.length} critical tyre alert${critical.length===1?'':'s'} in the current browser database.\n\n${critical.map(x=>`• ${x[0]} · ${x[1]} · ${x[2]} — RTD ${x[5]} mm`).join('\n')||'No critical tyres are currently recorded.'}\n\nFor a safety-critical decision, verify the physical tyre and your approved operating procedure before returning a vehicle to service.`;
if(/breakdown|break down|stranded|failure/.test(l))return `Current breakdown snapshot: ${open.length} open case${open.length===1?'':'s'}.\n\n${open.map(x=>`• ${x[0]} · ${x[1]} · ${x[3]} · ${x[4]} priority`).join('\n')||'No open breakdowns are recorded.'}`;
if(/inspection|inspect|check tyre|rtd/.test(l))return `For a tyre inspection, record the vehicle, tyre position/ID, date and inspector, then capture the RTD readings and defects. Where two RTD readings are taken, use the lowest reading for the decision. Do not rely on the assistant alone for legal or safety-critical limits; follow Milestone's approved inspection procedure and applicable regulations.`;
if(/service|what does milestone|client|customer|retread|scrap/.test(l))return `Milestone's operations workflow covers fleet/vehicle records, tyre tracking, inspections, breakdowns, retreads and scrap. For a client, I can also explain tyre services, inspection requirements, retread workflow, workshop processes and how to request assistance. Give me the specific service or problem and I’ll guide you.`;
if(/how many|count|fleet|vehicle/.test(l))return `The current browser database contains ${d.vehicles.length} vehicles, ${d.tyres.length} tyres, ${d.inspections.length} inspections, ${d.breakdowns.length} breakdown records, ${d.retreads.length} retread jobs and ${d.scrap.length} scrap records.`;
if(/hello|hi|hey/.test(l))return mode==='client'?'Hello. I’m the Milestone AI Assistant. I can help with tyres, inspections, retreads, breakdowns, workshop questions and general client support. What can I help you with?':'Hello. I’m ready to help with Milestone operations. Ask me about fleet, tyres, RTD, inspections, breakdowns, retreads, scrap or reporting.';
return `I can help with Milestone fleet and tyre operations, client questions, inspection workflows, RTD interpretation, breakdown triage, retreads, scrap and management reporting.\n\nI’m currently in local assistant mode on this static site. Once the secure AI backend is connected, I can answer open-ended questions with a full language model while still using Milestone's operational context.`}
async function ask(q){add(q,'user');history.push({role:'user',content:q});$('msTyping').classList.add('show');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,mode,context:context(),history:history.slice(-12)})});if(!r.ok)throw Error('offline');const j=await r.json();const a=j.text||j.output||j.message;if(!a)throw Error('empty');add(a,'bot');history.push({role:'assistant',content:a})}catch(e){const a=localAnswer(q);add(a,'bot');history.push({role:'assistant',content:a})}finally{$('msTyping').classList.remove('show')}}
$('msLaunch').onclick=()=>{$('msPanel').classList.toggle('open');if($('msPanel').classList.contains('open')&&!$('msMsgs').children.length){add(mode==='client'?'Hello. I’m the Milestone AI Assistant. I can help with tyres, inspections, retreads, breakdowns, workshop questions and general client support.':'Hello. I’m the Milestone AI Assistant. Ask me anything about the fleet, tyre register, inspections, breakdowns, retreads, scrap or reports.','bot')}};$('msClose').onclick=()=>$('msPanel').classList.remove('open');
root.querySelectorAll('.ms-mode button').forEach(b=>b.onclick=()=>{root.querySelectorAll('.ms-mode button').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;add(mode==='client'?'Client mode selected. I’ll focus on customer-friendly answers and service guidance.':'Staff mode selected. I’ll focus on operational and workshop support.','bot')});
root.querySelectorAll('.ms-quick button').forEach(b=>b.onclick=()=>ask(b.dataset.q));$('msForm').onsubmit=e=>{e.preventDefault();const q=$('msInput').value.trim();if(!q)return;$('msInput').value='';ask(q)};$('msInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('msForm').requestSubmit()}});
})();